version: '3.9'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      PORT: 3000
    ports:
      - "8080:3000"

  db:
    image: postgres:10.4
    ports:
      - "35000:5432"
    environment:
      DB_USER: postgres
      DB_PASSWORD: vini81342714
      DB_NAME: db
      DB_HOST: localhost

  redis:
    image: bitnami/redis:latest
    expose:
      - 6379
    environment:
      REDIS_PASSWORD: password