version: '3.9'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - redis
    environment:
      DATABASE_URL: postgres://postgres:vini81342714@localhost:5433/db
      PORT: 3000
    ports:
      - "8080:3000"